-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 17:46:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movie
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movie` ;

-- -----------------------------------------------------
-- Schema movie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie` DEFAULT CHARACTER SET utf8mb3 ;
USE `movie` ;

-- -----------------------------------------------------
-- Table `movie`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie`.`genres` ;

CREATE TABLE IF NOT EXISTS `movie`.`genres` (
  `genre_id` INT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `movie`.`title_basics` (
  `tconst` CHAR(10) NOT NULL,
  `primary_title` VARCHAR(250) NULL DEFAULT NULL,
  `start_year` FLOAT NULL DEFAULT NULL,
  `created_on` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_on` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `runtime` INT NULL DEFAULT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie`.`ratings` ;

CREATE TABLE IF NOT EXISTS `movie`.`ratings` (
  `tconst` CHAR(10) NOT NULL,
  `number_of_votes` INT NULL DEFAULT NULL,
  `created_on` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_on` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `average_rating` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie`.`title_genres` ;

CREATE TABLE IF NOT EXISTS `movie`.`title_genres` (
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie`.`tmdb_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie`.`tmdb_data` ;

CREATE TABLE IF NOT EXISTS `movie`.`tmdb_data` (
  `imdb_id` CHAR(10) NOT NULL,
  `adult` DOUBLE NULL DEFAULT NULL,
  `backdrop_path` TEXT NULL DEFAULT NULL,
  `belongs_to_collection` TEXT NULL DEFAULT NULL,
  `budget` FLOAT NULL DEFAULT NULL,
  `genres` TEXT NULL DEFAULT NULL,
  `homepage` TEXT NULL DEFAULT NULL,
  `id` DOUBLE NULL DEFAULT NULL,
  `original_language` TEXT NULL DEFAULT NULL,
  `original_title` TEXT NULL DEFAULT NULL,
  `overview` TEXT NULL DEFAULT NULL,
  `popularity` DOUBLE NULL DEFAULT NULL,
  `poster_path` TEXT NULL DEFAULT NULL,
  `production_companies` TEXT NULL DEFAULT NULL,
  `production_countries` TEXT NULL DEFAULT NULL,
  `release_date` TEXT NULL DEFAULT NULL,
  `revenue` FLOAT NULL DEFAULT NULL,
  `runtime` DOUBLE NULL DEFAULT NULL,
  `spoken_languages` TEXT NULL DEFAULT NULL,
  `status` TEXT NULL DEFAULT NULL,
  `tagline` TEXT NULL DEFAULT NULL,
  `title` TEXT NULL DEFAULT NULL,
  `video` DOUBLE NULL DEFAULT NULL,
  `vote_average` DOUBLE NULL DEFAULT NULL,
  `vote_count` DOUBLE NULL DEFAULT NULL,
  `certification` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`imdb_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
