-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 16:45:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movie
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movie` ;

-- -----------------------------------------------------
-- Schema movie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie` DEFAULT CHARACTER SET utf8 ;
USE `movie` ;

-- -----------------------------------------------------
-- Table `movie`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie`.`genres` ;

CREATE TABLE IF NOT EXISTS `movie`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `movie`.`title_basics` (
  `tconst` CHAR(10) NOT NULL,
  `primary_title` VARCHAR(250) NULL,
  `start_year` FLOAT NULL,
  `created_on` DATETIME NULL DEFAULT NOW(),
  `updated_on` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  `runtime` INT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie`.`ratings` ;

CREATE TABLE IF NOT EXISTS `movie`.`ratings` (
  `tconst` CHAR(10) NOT NULL,
  `number_of_votes` INT NULL,
  `created_on` DATETIME NULL DEFAULT NOW(),
  `updated_on` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  `average_rating` FLOAT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie`.`title_genres` ;

CREATE TABLE IF NOT EXISTS `movie`.`title_genres` (
  `tconst` INT NOT NULL,
  `genre_id` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
